version: "3.8"
services:
  mongodb:
    image : mongo
    container_name: mongodb_sprc_hw2
    environment:
      - PUID=1000
      - PGID=1000
      # - MONGO_INITDB_ROOT_USERNAME=root
      # - MONGO_INITDB_ROOT_PASSWORD=pass12345
    volumes:
      - mongodb_volume_sprc_hw2:/data/db
    networks:
      - mongodb_network_sprc_hw2
    ports:
      - 27016:27017
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    container_name: mongo-express_sprc_hw2
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      # - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      # - ME_CONFIG_MONGODB_ADMINPASSWORD=pass12345
      # - ME_CONFIG_BASICAUTH_USERNAME=admin
      # - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    volumes:
      - mongodb_volume_sprc_hw2
    depends_on:
      - mongodb
    networks:
      - mongodb_network_sprc_hw2
    ports:
      - 8081:8081
    restart: unless-stopped

volumes:
  mongodb_volume_sprc_hw2:
    name: mongodb_volume_sprc_hw2

networks:
  mongodb_network_sprc_hw2:
    name: mongodb_network_sprc_hw2
